# Generated by Django 6.0 on 2026-02-12 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(default='default_profile.jpg', upload_to='profile_pics/')),
                ('city', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Description des services (max 500 caractères)', max_length=500)),
                ('years_experience', models.IntegerField(blank=True, help_text="Années d'expérience", null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Tarif horaire indicatif (GNF)', max_digits=10, null=True)),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('busy', 'Occupé'), ('absent', 'Absent')], default='available', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='identity_docs/')),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('completed_jobs', models.IntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='services.servicecategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Prestataire',
                'verbose_name_plural': 'Profils Prestataires',
                'ordering': ['-is_premium', '-average_rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='profiles.providerprofile')),
            ],
            options={
                'verbose_name': 'Image Portfolio',
                'verbose_name_plural': 'Images Portfolio',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
